WAVE_TIME_THRESHOLD = 30_000
WAVE_KILL_THRESHOLD = 10
WAVE_SPEED_FACTOR = 0.2
WAVE_SPAWN_MIN = 1500
WAVE_SPAWN_MIN_CAP = 600
WAVE_FIGHTER_BASE = 30
WAVE_FIGHTER_INC = 10
WAVE_FIGHTER_CAP = 80
WAVE_SPAWN_DEC = 150

WAVE_KAMIKAZE_BASE = 10
WAVE_KAMIKAZE_INC = 4
WAVE_KAMIKAZE_CAP = 40

WAVE_GUNNER_MIN_WAVE = 3
WAVE_GUNNER_BASE = 25
WAVE_GUNNER_INC = 4
WAVE_GUNNER_CAP = 50

WAVE_STRIKER_MIN_WAVE = 6
WAVE_STRIKER_BASE = 20
WAVE_STRIKER_INC = 4
WAVE_STRIKER_CAP = 40

WAVE_INTERCEPTOR_MIN_WAVE = 10
WAVE_INTERCEPTOR_BASE = 15
WAVE_INTERCEPTOR_INC = 4
WAVE_INTERCEPTOR_CAP = 35
